### ISSUE TITLE
What is the licence for this code ?

### ISSUE THREAD

**Issue by njeudy** [bista-sales/multi_level_navigation#1]
Hello, 

This code is free I think but what is the licence for it ? AGPL ? GPL ? 
I need to make small improvement on it and with to work on it ..

Thanks a lot.

**Comment by bistaray** [comment]
@njeudy - sorry for the delay responding.  I am helping now with repository management.

For any version before v9, the license is GPL-3.

For version v9, the license is LGPL-3.

Let me know if I can close this issue.
